language: node_js

node_js:
  - node
  - '8'

services:
  - mongodb

install:
  - npm install -g gulp
  - npm install
  - ./node_modules/protractor/bin/webdriver-manager update

before_script:
  - npm run-script seed
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - npm start &
  - sleep 5

script:
  - npm run-script test
  - npm run-script lint
